### ISSUE TITLE
A corriger pour les URL

### ISSUE THREAD

**Issue by Soro08** [hayagoldberg/MikvahProject#14]
https://github.com/hayagoldberg/MikvahProject/blob/478688c90a4dec77a9179394f3fdbd508bde7bda/website/urls.py#L7C1-L18C91

Ce qu'il faut savoir des urls:

`path('client_page/', views.client_page_view, name='client_page'),`
- `'client_page/'` ce que le client voir dans le navigateur
- `name='client_page'` utiliser par django pour faire le lien avec la vue en question

Tu dois changer `'client_page/'` par `'client-page/'` pour faire simple, remplacer `_` par des `-` pour la partie client.

Faire pareil pour tous les urls cela facilite le référencement.

**Comment by hayagoldberg** [comment]
done
